export enum RepositoryEnums {
  FACILITY = 'facility',
  CLASSIFICATION = 'classification',
  FACILITY_STRUCTURE = 'facility_structure',
  FACILITY_HISTORY = 'facility_history',
  CLASSIFICATION_HISTORY = 'classification_history',
  FACILITY_STRUCTURE_HISTORY = 'facility_structure_history',
  TYPES = 'TYPES',
  COMPONENTS = 'COMPONENTS',
  ROOM = 'ROOM',
  ROOM_HISTORY = 'ROOM_HISTORY',
  ASSET = 'ASSET',
  ORGANIZATION = 'ORGANIZATION',
  INFRA = 'INFRA',
  EXCEL_IMPORT = 'EXCEL_IMPORT',
  SYSTEMS = 'SYSTEMS',
  SYSTEM_LAZY_LOADING = 'SYSTEM_LAZY_LOADING',
  LAZY_LOADING = 'lazyLoading',
  SYSTEM_COMPONENT = 'SYSTEM_COMPONENT',
}
